spring:
  application:
    name: clickhouse-spring-data-demo
  datasource:
    username: demo_user
    password: demo_user
    url: "jdbc:mysql://localhost:9004/spring_demo?serverTimezone=UTC"
    hikari:
      auto-commit: false
